name: Continuos Deployment workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use SSH key
        run: |
         mkdir -p ~/.ssh/
         echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/z1_key
         sudo chmod 600 ~/.ssh/z1_key
      - name: Git config
        run: |
         git config --global user.email "cd-user@my-app.com"
         git config --global user.name "cd-user"
      
      - name: Install dependencies
        run: yarn

      - name: Run esLint
        run: yarn lint

      - name: Build docs
        run: yarn build